---
name: konversation-qtquick
version: "0.0"
summary: IRC client
description: Konversation is an IRC client which gives you speedy access to Freenode network's channels, where you will find support for most distributions. Its defaults are such that it needs no configuration other than telling it the name of your distribution channel, to get started.
confinement: devmode
grade: devel

apps:
    konversation:
        command: launch konversation
        plugs:
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio

slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.konversation
        bus: session

parts:
    helper:
        plugin: dump
        prime:
        - launch
        source: helper
    konversation:
        plugin: cmake
        stage-packages: [qml-module-org-kde-kirigami2]
        build-packages:
        - extra-cmake-modules
        - kdoctools-dev
        - kio-dev
        - libkf5archive-dev
        - libkf5bookmarks-dev
        - libkf5config-dev
        - libkf5configwidgets-dev
        - libkf5coreaddons-dev
        - libkf5crash-dev
        - libkf5dbusaddons-dev
        - libkf5emoticons-dev
        - libkf5globalaccel-dev
        - libkf5i18n-dev
        - libkf5iconthemes-dev
        - libkf5idletime-dev
        - libkf5notifications-dev
        - libkf5notifyconfig-dev
        - libkf5parts-dev
        - libkf5solid-dev
        - libkf5sonnet-dev
        - libkf5wallet-dev
        - libkf5widgetsaddons-dev
        - libkf5windowsystem-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libqca-qt5-2-dev
        - qtbase5-dev
        - qtdeclarative5-dev
        - libkf5package-dev
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
        stage:
        - "-usr/bin/X11"
        - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
        prime:
        - "$exclusion"
        source: https://anongit.kde.org/konversation.git
        source-branch: wip/qtquick
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
